### ISSUE TITLE
Login/Berechtigungen

### ISSUE THREAD

**Issue by Hannes-Neunaber** [szut-fa19d/nhs-d#11]
### User-Story

Als LOREM IPSUM möchte ich, dass nur berechtigte Personen Zugriff auf unsere interne Software haben. Der Zugriff muss über ein Login-System gelöst werden und abhängig von der Benutzergruppe die dem Nutzer zugeordnet ist, werden bestimmte Bereiche freigeschaltet bzw. gesperrt. Nutzer mit der Administration-Berechtigung haben die Möglichkeit einen neuen Benutzer anzulegen und für das System freizuschalten. 

**Akzeptanzkriterien**
- [ ] A_1: Der Nutzer existiert und muss sich anmelden können
- [ ] A_2: Dem Nutzer ist eine Benutzergruppe zugeordnet
- [ ] A_3: Bei der Anzeige von Daten werden die Berechtigungen des Nutzers überprüft

**Tasks**
- [x] T_1: Entwerfen einer “Login.fxml” Datei
- [x] T_2: Entwerfen von “AllUserView.fxml”, “UserView.fxml”, “AllUserGroupView.fxml” und “UserGroupView.fxml”
- [x] T_3: Einfügen einer User Tabelle mit folgenden Feldern in die Datenbank:

 1. id
 2. name
 3. password
 4. group

- [x] T_4: Einfügen einer usergroup Tabelle mit folgenden Feldern in die Datenbank:

 1. id
 2. name
 3. rights

- [x] T_5: Erstellen der entsprechenden Models und DAOs:

 1. User
 2. UserDAO
 3. Group
 4. GroupDAO

- [x] T_6: Erstellen einer “RightManagement” Klasse (Singleton?)

 1. user
 2. Login()
 3. Logout()
 4. hasRight()

- [ ] T_7: Abfragen der Berechtigungen in den entsprechenden Controllern

**Testfälle**
TF1_: Zugriff auf die Software: “Login” 
Vorbedingung: Benutzer wurde angelegt / Benutzer existiert
auszuführende Testschritte:
Benutzer meldet sich mit seinem Passwort in der Software an
erwartetes Ergebnis:
Benutzer hat Zugriff auf die Software

TF2_: Zugriff gewährt auf bestimmten Bereich z.B. Patientendaten  
Vorbedingung: Benutzer ist eingeloggt, Benutzer hat Zugriffsrechte auf die Patientendaten
auszuführende Testschritte:
Benutzer greift auf Patientendaten zu
erwartetes Ergebnis:
Benutzer kriegt Einsicht über die Patientendaten

TF3_: Zugriff nicht gewährt für bestimmten Bereich z.B. Patientendaten  
Vorbedingung: Benutzer ist eingeloggt, Benutzer hat keine Zugriffsrechte auf die Patientendaten
auszuführende Testschritte:
Benutzer greift auf Patientendaten zu
erwartetes Ergebnis:
Benutzer kriegt keine Einsicht über die Patientendaten

**Comment by JLNPWRLFT** [comment]
Ein weitere Punkt: User müssen angelegt sowie gelöscht und bearbeitet werden können. (nur von admins tho)
