### ISSUE TITLE
Behandlungs- und Patientendaten sperren/entsperren

### ISSUE THREAD

**Issue by JLNPWRLFT** [szut-fa19d/nhs-d#12]
Als LOREM IPSUM möchte ich, dass unsere Behandlungs- und Patientendaten gesperrt werden können um die gesetzlichen Vorschriften einzuhalten. Ebenfalls soll die Möglichkeit bestehen, einen Patienten komplett zu sperren, was darin resultiert, dass die Patientendaten sowie alle Daten seiner zugehörigen Behandlungen gesperrt werden. Darüber hinaus möchte ich sowohl die Behandlungs- und Patientendaten als auch Patienten komplett wieder entsperren können. 

## Akzeptanzkriterien
- [x] **A_1**:  Patientendaten (Name, Geb., …) können gesperrt und entsperrt werden
- [x] **A_2**:  Patient komplett sperren
- [x] **A_3**:   Wenn ein Patient komplett gesperrt wird, werden alle zugehörigen Behandlungen zu ihm auch gesperrt bzw. entsperrt sobald dieser Patient entsperrt wird. 
- [x] **A_4**: Behandlungsdaten können gesperrt und entsperrt werden.

## Tasks
- [x] **T_1**:  Erstellen einer Methode die alle Daten(Behandlungen, Patientendaten) in Verbindung zum Patienten selektiert. Erhält die Patienten ID.
- [x] **T_2**: Die folgenden Methode erhalten ein Kennzeichen(Behandlung oder Patientendaten) dazu noch die ID des zu sperrenden Datensatzes. Anhand der übergeben Daten wird eine der folgenden Methoden Versionen ausgeführt. (Überladung)

  - [x] **T_2_1**: Erstellen einer Methode die Patientendaten sperrt. (“P”,” ID)
  - [x] **T_2_2**: Erstellen einer Methode die Patientendaten entsperrt. (“P”, ID)
  - [x] **T_2_3**: Erstellen einer Methode die Behandlungsdaten sperrt. (“B”, ID)
  - [x] **T_2_4**: Erstellen einer Methode die Behandlungsdaten entsperrt.(“B”, ID)

### TF1_:  Patient komplett sperren

**Vorbedingung:** Beliebigen Patient auswählen.

**auszuführende Testschritte:**
1. Patient sperren

**erwartetes Ergebnis:**
1. Der Patient wird gesperrt und mit einem Gesperrt-Kennzeichen vermerkt
2. Alle Behandlungen zu diesem Patient werden gesperrt und mit einem Gesperrt-Kennzeichen vermerkt

### TF2_:  Patient komplett entsperren

**Vorbedingung:**  Gesperrten Patient auswählen

**auszuführende Testschritte:**
1. Patient entsperren

**erwartetes Ergebnis:**
1. Der Patient wird entsperrt und das Gesperrt-Kennzeichen wird entfernt
2. Alle Behandlung von diesem Patienten werden entsperrt und das Gesperrt-Kennzeichen wird entfernt

### TF3_:  Patientendaten sperren

**Vorbedingung:**  Patientendaten sind nicht gesperrt

**auszuführende Testschritte:**
1. Patientendaten sperren

**erwartetes Ergebnis:**
1. Patientendaten werden gesperrt und mit einem Gesperrt-Kennzeichen vermerkt

### TF4_:  Patientendaten entsperren

**Vorbedingung:**  Patientendaten sind gesperrt

**auszuführende Testschritte:**
1. Patientendaten entsperren

**erwartetes Ergebnis:**
1. Patientendaten werden entsperrt und das Gesperrt-Kennzeichen wird entfernt. 

### TF5_:   Behandlungsdaten sperren

**Vorbedingung:**  Behandlungsdaten sind nicht gesperrt

**auszuführende Testschritte:**
1. Behandlungsdaten sperren

**erwartetes Ergebnis:**
1. Behandlungsdaten werden gesperrt und mit einem Gesperrt-Kennzeichen vermerkt

### TF6_:   Behandlungsdaten entsperren

**Vorbedingung:** Behandlungsdaten sind gesperrt

**auszuführende Testschritte:**
1. Behandlungsdaten entsperren

**erwartetes Ergebnis:**
1. Behandlungsdaten werden entsperrt und das Gesperrt-Kennzeichen wird entfernt.

**Comment by FunctionDJ** [comment]
>  T_2_3: Erstellen einer Methode die Behandlungsdaten sperrt. (“B”, ID)

Müssen Behandlungsdaten einzeln sperrbar sein, oder würde auch eine Sperrmarkierung am Patienten reichen, die sämtliche Behandlungsdaten sperrt?
