### ISSUE TITLE
Loggen von Änderungen / Sperrungen / Entsperrungen

### ISSUE THREAD

**Issue by JLNPWRLFT** [szut-fa19d/nhs-d#14]
Als LOREM IPSUM möchte ich, dass Änderungen an Datensätzen geloggt werden. Es sollen Änderungen, Sperrungen, Entsperrungen, und Ersteller geloggt werden. Auch benötigen wir eine View zum ansehen der Log-Daten.

## Akzeptanzkriterien
- [ ] **A_1**: Patienten Änderungen werden geloggt .
- [ ] **A_2**: Behandlungs Änderungen werden geloggt .
- [ ] **A_3**: Behandlungs Sperrungen werden geloggt .
- [ ] **A_4**: Patienten Sperrungen werden geloggt .
- [ ] **A_5**: Erstellung von Patienten und Behandlungen werden geloggt.
- [ ] **A_6**: Die Änderungen zu Behandlungen und Patienten müssen eingesehen werden können.

## Tasks
- [x] **T_1**: Erstellen einer Log Tabelle in der Datenbank mit folgenden Feldern:
  - id
  - timestamp
  - type
  - obj_id
  - desc
- [x] **T_2**: Erstellen von Log und LogDAO

### TF1_:  Loggen von Behandlungs Änderungen

**Vorbedingung:** Auswahlmöglichkeit ist vorhanden, User-Story a und b sind abgeschlossen

**auszuführende Testschritte:**
1. Behandlung ändern

**erwartetes Ergebnis:**
1. Die Änderung erscheint im Log

### TF2_:  Loggen von Patienten Änderungen

**Vorbedingung:** Patient ist angelegt und der User hat die Rechte zum bearbeiten.

**auszuführende Testschritte:**
1. Patient ändern 

**erwartetes Ergebnis:**
1. Die Änderung erscheint im Log

### TF3_:  Loggen von Patienten Sperrungen / Entsperrungen

**Vorbedingung:** Patient ist angelegt und der User hat die Rechte zum Sperren/Entsperren von Patienten

**auszuführende Testschritte:**
1. Patient sperren/entsperren

**erwartetes Ergebnis:**
1. Die Änderung erscheint im Log

### TF4_:  Loggen von Behandlung Sperrungen / Entsperrungen 

**Vorbedingung:** Behandlung ist angelegt und der User hat die Rechte zum Sperren/Entsperren von Behandlungen

**auszuführende Testschritte:**
1. Behandlung sperren/entsperren

**erwartetes Ergebnis:**
1. Die Änderung erscheint im Log

### TF5_:  Darstellung vom Log

**Vorbedingung:** Es bestehen Datensätze zu Behandlungen und Patienten.

**auszuführende Testschritte:**
1. Öffnen der Log View

**erwartetes Ergebnis:**
1. Alle Log Einträge werden angezeigt (neuste zuerst)
