### ISSUE TITLE
Ansicht für die Auflistung aller Pfleger/-innen

### ISSUE THREAD

**Issue by bebetepp** [szut-fa19d/nhs-d#5]
Als LOREM IPSUM möchte ich über die Navigationsleiste auf einer Auflistung aller Pfleger sowie Pflegerinnen gelangen. Diese Ansicht enthält folgende Daten über die Pfleger/Pflegerinnen:
- ID
- Vorname
- Nachname
- Telefonnummer

## Akzeptanzkriterien
- [ ] **A_1**: Alle Pfleger werden mit ID, Vorname, Nachname und Telefonnummer aufgelistet
- [ ] **A_2**: Die Navigationsleiste enthält einen Button um die Seite zu öffnen

## Tasks
- [x] **T_1**: Modelklasse Caregiver erstellen: abgeleitet von Person, Konstruktoren mit und ohne 
PflegerID
- [x] **T_2**: CaregiverDAO erstellen
- [x] **T_3**: Datenbank mit Tabelle Caregiver anlegen
- [x] **T_4**: Erstellen eines CaregiverControllers: stellt die Methoden zum Anzeigen, Ändern, Löschen 
und Hinzufügen bereit.
- [ ] **T_5**: Navigationsbutton hinzufügen

### TF1_: Alle Pfleger anzeigen

**Vorbedingung:**
Der Nutzer hat im Hauptfenster der Anwendung die Option Pfleger/innen ausgewählt

**auszuführende Testschritte:**
keine

**erwartetes Ergebnis:**
Es werden all Pfleger, die in der Datenbank gespeichert sind, mit ihrer ID, Nachnamen, Vornamen und Telefonnummer in einer TableView angezeigt

### TF2_: Pflegerdaten ändern

**Vorbedingung:**
Der Nutzer hat im Hauptfenster der Anwendung die Option Pfleger/innen ausgewählt

**auszuführende Testschritte:**
1. Der User wählt per Doppelklick auf einen Nachnamen einen 
Pfleger aus
2. Der User ändert den Nachnamen
3. Der User beendet die Eingabe mit der Entertaste

**erwartetes Ergebnis:**
1. Der geänderte Nachname wird in der Tableview angezeigt
2. Der geänderte Nachname wird in der Datenbank gespeichert

### TF3_: Pfleger anlegen

**Vorbedingung:**
Der Nutzer hat im Hauptfenster der Anwendung die Option Pfleger/innen 
ausgewählt

**auszuführende Testschritte:**
1. Der Nutzer gibt den Nachnamen, Vornamen und Telefonnummer in die dafür 
vorgesehenen Textfelder ein
2. Der Nutzer klickt auf den Hinzufügen Button

**erwartetes Ergebnis:**
1. Der neue Patient wird mit allen eingetragenen Daten sowie einer automatisch erstellten ID als letzter Eintrag in der Tableview angezeit
2. Der neue Patient wurde in der Datenbank gespeichert

### TF4_: Pfleger löschen

**Vorbedingung:** 
Es existiert ein Button um den Pfleger zu löschen oder das Löschen wird 
durchgeführt, durch die ENTF-Taste. Vor dem Löschen erscheint eine Meldung, in der gefragt wird ob man diesen User wirklich löschen möchte.

**auszuführende Testschritte:**
1. Der User wählt einen Pfleger aus, den er löschen möchte
2. Der User betätigt die ENTF-Taste oder klickt auf den Löschen-Button
3. Der User bestätigt, dass er diesen User wirklich löschen möchte

**erwartetes Ergebnis:**
1. Der Pfleger wird aus der Tableview entfernt.
2. Der Pfleger wird aus der Datenbank entfernt.
