### ISSUE TITLE
Loggen von Änderungen für Patienten und Behandlungen

### ISSUE THREAD

**Issue by Hannes-Neunaber** [szut-fa19d/nhs-d#6]
###  User-Story

Als LOREM IPSUM möchte ich, dass Änderungen an Datensätzen geloggt werden. Es sollen Änderungen ,Sperrungen/Entsperrungen, und Ersteller geloggt werden. Auch benötigen wir eine View zum ansehen der Log-Daten.

**Akzeptanzkriterien**

- [ ] A_1: Patienten Änderungen werden geloggt .
- [ ] A_2: Behandlungs Änderungen werden geloggt .
- [ ] A_3: Behandlungs Sperrungen werden geloggt .
- [ ] A_4: Patienten Sperrungen werden geloggt .
- [ ] A_6: Erstellung von Patienten und Behandlungen werden geloggt.
- [ ] A_6: Die Änderungen zu Behandlungen und Patienten müssen eingesehen werden können.

**Tasks**
- [ ] T_1: Erstellen einer Log Tabelle in der Datenbank mit folgenden Feldern:
1.	id
2.	timestamp
3.	type
4.	obj_id
5.	desc

- [ ] T_2: Erstellen von Log und LogDAO

**Testfälle**
TF1_: Loggen von Behandlungs Änderungen
Vorbedingung: Auswahlmöglichkeit ist vorhanden, User-Story a und b sind abgeschlossen
auszuführende Testschritte: Behandlung ändern
erwartetes Ergebnis: Die Änderung erscheint im Log

TF2:  Loggen von Patienten Änderungen
Vorbedingung: Patient ist angelegt und der User hat die Rechte zum bearbeiten.
auszuführende Testschritte: Patient ändern
erwartetes Ergebnis: Die Änderung erscheint im Log

TF3:  Loggen von Patienten Sperrungen\Entsperrungen Änderungen
Vorbedingung: Patient ist angelegt und der User hat die Rechte zum Sperren/Entsperren von Patienten
auszuführende Testschritte: Patient sperren/entsperren
erwartetes Ergebnis: Die Änderung erscheint im Log

TF4:  Loggen von Behandlung Sperrungen\Entsperrungen  Änderungen
Vorbedingung: Behandlung ist angelegt und der User hat die Rechte zum Sperren/Entsperren von Behandlungen
auszuführende Testschritte: Behandlung sperren/entsperren
erwartetes Ergebnis: Die Änderung erscheint im Log

TF4:  Anzeigen von Änderungs Logs
Vorbedingung: Es bestehen Datensätze zu Behandlungen und Patienten.
auszuführende Testschritte: Öffnen der Log View
erwartetes Ergebnis: Alle Log Einträge werden angezeigt

**Comment by bebetepp** [comment]
Wir haben die User Story zweimal als Issue. Ich schließe diesen.

**Comment by FunctionDJ** [comment]
Dieses Issue wird ersetzt [durch dieses.](#14)
