### ISSUE TITLE
Programm benötigt Integration von Pflegern (View, Management, relationale Integrität)

### ISSUE THREAD

**Issue by FunctionDJ** [szut-fa19d/nhs-d#8]
Als LOREM IPSUM  möchte ich in der Ansicht von einer einzelnen Behandlung folgende Daten über den zugehörigen Pfleger bzw. Pflegerin dargestellt bekommen: 
- Vorname
- Nachname
- Telefonnummer

## Akzeptanzkriterien
- [ ] **A_1**: Pfleger bzw. Pflegerin können zu einer Behandlung hinzugefügt werden (= Modul c muss fertig sein)
- [ ] **A_2**: Zu einer Behandlung wird der zugehörige Pfleger bw. Pflegerin angezeigt (Vorname, Nachname, Telefonnummer)

## Tasks
- [ ] **T_1**: Model Treatment erweitern um einen oder mehrere Caregiver zuweisen zu können.
- [ ] **T_2**: “TreatmentView” um die benötigten felder erweitern
  - Vorname
  - Nachname
  - Telefonnummer

### TF1_: Pflegerdaten anzeigen

**Vorbedingung:**
Der Nutzer hat eine Behandlung in der Einzelansicht geöffnet.

**auszuführende Testschritte:**
keine

**erwartetes Ergebnis:**
Der zugehörige Pfleger wird mit seinem Vorname, Nachnamen und Telefonnummer angezeigt

### TF2_: Pflegerdaten ändern

**Vorbedingung:**
Der Nutzer hat eine Behandlung in der Einzelansicht geöffnet.

**auszuführende Testschritte:**
1. Der Nutzer wählt einen neuen Pfleger aus.
2. Der Nutzer speichert die Änderungen, indem er auf “Ändern” klickt.

**erwartetes Ergebnis:**
1. Der Pfleger wird in der Datenbank geändert
