### ISSUE TITLE
Sperren von Patienten und Behandlungsdaten

### ISSUE THREAD

**Issue by Hannes-Neunaber** [szut-fa19d/nhs-d#9]
### User-Story

Als LOREM IPSUM möchte ich, dass unsere Behandlungs- und Patientendaten gesperrt werden können um die gesetzlichen Vorschriften einzuhalten. Ebenfalls soll die Möglichkeit bestehen, einen Patienten komplett zu sperren, was darin resultiert, dass die Patientendaten sowie alle Daten seiner zugehörigen Behandlungen gesperrt werden. Darüber hinaus möchte ich sowohl die Behandlungs- und Patientendaten als auch Patienten komplett wieder entsperren können. 

**Akzeptanzkriterien**

- [x] A_1: Patientendaten (Name, Geb., …) können gesperrt und entsperrt werden
- [x] A_2:  Patient komplett sperren
- [x] A_2: Wenn ein Patient komplett gesperrt wird, werden alle zugehörigen Behandlungen zu ihm auch gesperrt bzw. entsperrt sobald dieser Patient entsperrt wird. 
- [x] A_3: Behandlungsdaten können gesperrt und entsperrt werden.

**Tasks**

- [x] T_1: Erstellen einer Methode die alle Daten(Behandlungen, Patientendaten) in Verbindung zum Patienten selektiert. Erhält die Patienten ID.

- [x] T_2: Die folgenden Methode erhalten ein Kennzeichen(Behandlung oder Patientendaten) dazu noch die ID des zu sperrenden Datensatzes. Anhand der übergeben Daten wird eine der folgenden Methoden Versionen ausgeführt. (Überladung)
  - T_2_1: Erstellen einer Methode die Patientendaten sperrt. (“P”,” ID)
  - T_2_2: Erstellen einer Methode die Patientendaten entsperrt. (“P”, ID)
  - T_2_3: Erstellen einer Methode die Behandlungsdaten sperrt. (“B”, ID)
  - T_2_4: Erstellen einer Methode die Behandlungsdaten entsperrt.(“B”, ID)

**Testfälle**

TF1_: Patient komplett sperren
Vorbedingung: Beliebigen Patient auswählen.
auszuführende Testschritte: Patient sperren
erwartetes Ergebnis: 
Der Patient wird gesperrt und mit einem Gesperrt-Kennzeichen vermerkt
Alle Behandlungen zu diesem Patient werden gesperrt und mit einem Gesperrt-Kennzeichen vermerkt

TF2_: Patient komplett entsperren
Vorbedingung: Gesperrten Patient auswählen
auszuführende Testschritte: Patient entsperren
erwartetes Ergebnis: 
Der Patient wird entsperrt und das Gesperrt-Kennzeichen wird entfernt
Alle Behandlung von diesem Patienten werden entsperrt und das Gesperrt-Kennzeichen wird entfernt

TF3_: Bearbeiten eines Gesperrten Patienten
Vorbedingung: Patient ist Gesperrt
auszuführende Testschritte: Versuchen den Gesperrten Patienten zu bearbeiten.
erwartetes Ergebnis: keine Änderungen werden gespeichert.

TF4_: Öffnen einer Gesperrten Behandlung
Vorbedingung: Behandlung ist gesperrt
auszuführende Testschritte: Behandlungs Details mit einem Doppelklick öffnen.
erwartetes Ergebnis: Behandlungs Details werden nicht geöffnet.

> Alte Testfälle die nicht mehr aktuell sind.
> TF4_: Patientendaten entsperren
> Vorbedingung: Patientendaten sind gesperrt
> auszuführende Testschritte: Patientendaten entsperren
> erwartetes Ergebnis: Patientendaten werden entsperrt und das Gesperrt-Kennzeichen wird entfernt. 
> 
> TF5_: Behandlungsdaten sperren
> Vorbedingung: Behandlungsdaten sind nicht gesperrt
> auszuführende Testschritte: Behandlungsdaten sperren
> erwartetes Ergebnis: Behandlungsdaten werden gesperrt und mit einem Gesperrt-Kennzeichen vermerkt
> 
> TF6_: Behandlungsdaten entsperren
> Vorbedingung: Behandlungsdaten sind gesperrt
> auszuführende Testschritte: Behandlungsdaten entsperren
> erwartetes Ergebnis: Behandlungsdaten werden entsperrt und das Gesperrt-Kennzeichen wird entfernt.
